import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { harness } from "./server-harness";
let h: Awaited<ReturnType<typeof harness>>;
beforeEach(async () => { h = await harness(); }); afterEach(async () => { await h.close(); });
describe("Adversarial support regressions", () => {
  it("counts attempts rather than supplied number", async () => { await h.role("student"); const args = { practiceId: "prac-mariana-fracciones", studentId: "mariana-lopez", exerciseId: "ex-frac-1", studentAnswer: "wrong", attemptNumber: 1 }; await h.call("submit_answer", args); expect((await h.call("submit_answer", args)).body.result.structuredContent.attemptNumber).toBe(2); });
  it("withholds correct options in all support levels", async () => { const p = (await h.state()).practices[0]; await h.role("student"); for (const e of p.exercises) { const hint = await h.call("get_hint", { practiceId: p.id, studentId: p.studentId, exerciseId: e.id }); expect(hint.body.result.structuredContent.hint).not.toContain(e.correctAnswer); for (const level of ["analogy", "step_by_step"]) { const result = await h.call("get_adaptive_explanation", { practiceId: p.id, studentId: p.studentId, exerciseId: e.id, level }); expect(result.body.result.structuredContent.explanation).not.toContain(e.correctAnswer); } } });
  it("denies cross-student evidence", async () => { await h.role("student", "luis-hernandez"); expect((await h.call("get_practice_result", { studentId: "mariana-lopez", practiceId: "prac-mariana-fracciones" })).body.result.isError).toBe(true); });
  it("denies cross-student exercise support", async () => { await h.role("student", "luis-hernandez"); expect((await h.call("get_hint", { studentId: "luis-hernandez", practiceId: "prac-mariana-fracciones", exerciseId: "ex-frac-1" })).body.result.isError).toBe(true); });
  it("requires current assigned exercise", async () => { const p = (await h.state()).practices[0]; await h.role("student"); expect((await h.call("submit_answer", { studentId: p.studentId, practiceId: p.id, exerciseId: p.exercises[1].id, studentAnswer: "wrong", attemptNumber: 1 })).body.result.isError).toBe(true); });
  it("normalizes oral answers", async () => { await h.role("student"); const result = await h.call("submit_answer", { studentId: "mariana-lopez", practiceId: "prac-mariana-fracciones", exerciseId: "ex-frac-1", studentAnswer: "dos cuartos", attemptNumber: 1 }); expect(result.body.result.structuredContent.isCorrect).toBe(true); });
});
