import { describe,it,expect,beforeEach,afterEach } from "vitest";
import { McpClient } from "@/lib/mcp/client";
import { harness } from "./server-harness";
let h: Awaited<ReturnType<typeof harness>>;beforeEach(async()=>{h=await harness();});afterEach(async()=>{await h.close();});
describe("Judge demo client consistency",()=>{
  it("loads practices from server and hides answer keys for student",async()=>{const c=new McpClient(h.base+"/mcp");await c.initializeDemo();expect((await c.snapshot()).practices).toHaveLength(1);await c.selectRole("student","mariana-lopez");const state=await c.snapshot();expect(state.students).toHaveLength(1);expect(state.practices[0].exercises[0].correctAnswer).toBe("");});
  it("creates a fresh isolated scenario on explicit reset",async()=>{const c=new McpClient(h.base+"/mcp");await c.initializeDemo();await c.generateAdaptivePractice("mariana-lopez","fracciones-equivalentes");expect((await c.snapshot()).practices.length).toBeGreaterThan(1);await c.initializeDemo(true);expect((await c.snapshot()).practices).toHaveLength(1);});
  it("waits for demo reset before exchanging actor role",async()=>{const c=new McpClient(h.base+"/mcp");await c.initializeDemo();await c.generateAdaptivePractice("mariana-lopez","fracciones-equivalentes");const reset=c.initializeDemo(true);const role=c.selectRole("student","mariana-lopez");await Promise.all([reset,role]);expect((await c.snapshot()).practices).toHaveLength(1);await expect(c.generateAdaptivePractice("mariana-lopez","fracciones-equivalentes")).rejects.toThrow();});
  it("reports real connection and tool catalog",async()=>{const c=new McpClient(h.base+"/mcp");expect((await c.checkConnection()).connected).toBe(true);expect(await c.listTools()).toHaveLength(15);});
  it("fails offline without local results",async()=>{const c=new McpClient("http://127.0.0.1:1/mcp");expect((await c.checkConnection()).connected).toBe(false);await expect(c.getStudentContext("mariana-lopez")).rejects.toThrow();await expect(c.listTools()).rejects.toThrow();});
  it("teacher publication is server visible to student",async()=>{const {createDraft}=await import("@/lib/learning/catalog");const c=new McpClient(h.base+"/mcp");await c.initializeDemo();const state=await c.snapshot();const draft=createDraft({subjectId:"matematicas",topicId:"fracciones-equivalentes",grade:3,objective:"Comparar fracciones",recipientId:"mariana-lopez",exerciseCount:5,difficulty:"easy",activityKind:"choice",initialSupport:"verbal"} as any);const published=await c.demoApi("/api/practices",draft);await c.selectRole("student","mariana-lopez");expect((await c.snapshot()).practices.some((p:any)=>p.id===published[0].id)).toBe(true);expect(state.practices).toHaveLength(1);});
});
