import {describe,it,expect,beforeEach,afterEach} from "vitest";
import {harness} from "./server-harness";
import {activePracticeForExercise} from "@/lib/learning/active-practice";
import {createDraft} from "@/lib/learning/catalog";
let h: Awaited<ReturnType<typeof harness>>;beforeEach(async()=>{h=await harness();});afterEach(async()=>{await h.close();});
describe("Practice scope and missing baseline regressions",()=>{
  it("selects active assignment when exercises share IDs",async()=>{const generated=await h.call("generate_adaptive_practice",{studentId:"mariana-lopez",topicId:"fracciones-equivalentes"});const p=(await h.state()).practices;expect(p).toHaveLength(2);const id=generated.body.result.structuredContent.practiceId;expect(activePracticeForExercise(p,"mariana-lopez",id,p[0].exercises[0].id)?.id).toBe(id);expect(activePracticeForExercise(p,"mariana-lopez",null,p[0].exercises[0].id)).toBeUndefined();});
  it("records support in chosen practice without contaminating another",async()=>{const g=await h.call("generate_adaptive_practice",{studentId:"mariana-lopez",topicId:"fracciones-equivalentes"});const id=g.body.result.structuredContent.practiceId;const p=(await h.state()).practices.find((p:any)=>p.id===id);await h.role("student");const support=await fetch(h.base+"/api/support",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+h.token()},body:JSON.stringify({practiceId:id,exerciseId:p.exercises[0].id,kind:"visual_hint"})});expect(support.status).toBe(200);for(const e of p.exercises)await h.call("submit_answer",{practiceId:id,studentId:p.studentId,exerciseId:e.id,studentAnswer:e.correctAnswer,attemptNumber:1});const result=(await h.call("complete_practice",{practiceId:id,studentId:p.studentId})).body.result.structuredContent;expect(result.evidence.hintsUsed).toBe(1);expect(result.evidence.supportEvents[0].kind).toBe("visual_hint");expect((await h.state()).practices.find((p:any)=>p.id==="prac-mariana-fracciones").status).toBe("pending");});
  it("reports first measurement without a fabricated baseline",async()=>{const draft=createDraft({subjectId:"espanol",topicId:"comprension-lectora",grade:3,objective:"Identificar idea principal",recipientId:"mariana-lopez",exerciseCount:3,difficulty:"easy",activityKind:"reading",initialSupport:"independent"});const response=await fetch(h.base+"/api/practices",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+h.token()},body:JSON.stringify(draft)});const [p]=await response.json();await h.role("student");for(const e of p.exercises)await h.call("submit_answer",{practiceId:p.id,studentId:p.studentId,exerciseId:e.id,studentAnswer:e.correctAnswer,attemptNumber:1});const evidence=(await h.call("complete_practice",{practiceId:p.id,studentId:p.studentId})).body.result.structuredContent.evidence;expect(evidence.baselineAvailable).toBe(false);expect(evidence.status).toBe("Primera medición");expect(evidence.improvementDelta).toBe(0);});
});
