/**
 * MACHTIA Adaptive Tutor - Didactic Text Signature Guard (v2 Adversarial Grade)
 *
 * Prevents unauthorized or arbitrary text synthesis by signing all pedagogical
 * responses generated by MIA. The /api/tts endpoint verifies this HMAC signature
 * to ensure that ONLY authentic, vetted educational explanations from MIA are synthesized.
 *
 * Security properties enforced:
 * 1. Text integrity (HMAC-SHA256 constant-time comparison).
 * 2. Signature expiration (15-minute TTL to prevent stale replay).
 * 3. Future timestamp rejection (max 60 seconds clock skew tolerance).
 * 4. Actor binding (bound to specific student or teacher actor id).
 * 5. Replay bounding (limits multiple playback calls of the same signature).
 * 6. Secret containment (secret exists purely on server, never exposed).
 */

import { createHmac, timingSafeEqual } from "node:crypto";

// Server-side secret (never exposed to client or browser bundles)
const HMAC_SECRET =
  process.env.MIA_HMAC_SECRET ||
  process.env.ELEVENLABS_API_KEY ||
  "machtia-internal-didactic-secret-v1";

const SIGNATURE_TTL_MS = 15 * 60 * 1000; // 15 minutes
const MAX_FUTURE_SKEW_MS = 60 * 1000;     // 60 seconds
const MAX_REPLAYS_PER_SIGNATURE = 5;      // Allow child to replay message up to 5 times

// In-memory sliding replay tracker: signature -> { count, expires }
const replayTracker = new Map<string, { count: number; expires: number }>();

function cleanupReplayTracker() {
  const now = Date.now();
  for (const [key, val] of replayTracker) {
    if (val.expires <= now) replayTracker.delete(key);
  }
}

/**
 * Normalizes text formatting before calculating signature to avoid whitespace discrepancies.
 */
function canonicalizeText(text: string): string {
  return text.trim().replace(/\s+/g, " ");
}

/**
 * Canonical welcome greeting for MIA companion.
 */
export const CANONICAL_WELCOME_TEXT =
  "Hola, soy MIA 👋\nTu compañera de aprendizaje.\nPregúntame lo que quieras aprender.\nAquí puedes preguntar, equivocarte y volver a intentar.";

/**
 * Checks whether text matches the official, static didactic welcome greeting.
 */
export function isCanonicalDidacticText(text: string): boolean {
  if (!text) return false;
  return canonicalizeText(text) === canonicalizeText(CANONICAL_WELCOME_TEXT);
}

/**
 * Generates an HMAC signature for an approved pedagogical text produced by MIA.
 * Format: v1.<timestamp>.<actorId>.<hmacHex>
 */
export function generateDidacticSignature(
  text: string,
  actorId: string = "student-mariana-1",
  customTimestamp?: number
): string {
  const canonical = canonicalizeText(text);
  const timestamp = customTimestamp ?? Date.now();
  const safeActorId = (actorId || "student-mariana-1").replace(/[:.]/g, "_");
  const payloadToSign = `v1:${canonical}:${safeActorId}:${timestamp}`;
  const hmac = createHmac("sha256", HMAC_SECRET).update(payloadToSign).digest("hex");
  return `v1.${timestamp}.${safeActorId}.${hmac}`;
}

export interface VerificationResult {
  valid: boolean;
  reason:
    | "VALID"
    | "CANONICAL_WELCOME"
    | "EXPIRED"
    | "FUTURE_TIMESTAMP"
    | "ACTOR_MISMATCH"
    | "TAMPERED_TEXT"
    | "INVALID_FORMAT"
    | "EMPTY_TEXT"
    | "REPLAY_EXCEEDED";
  actorId?: string;
  timestamp?: number;
  remainingReplays?: number;
}

/**
 * Detailed verification assessing signature validity, TTL, actor binding, and replay.
 */
export function verifyDidacticSignatureDetail(
  text: string,
  signature: string | null | undefined,
  expectedActorId?: string | null
): VerificationResult {
  if (!text) return { valid: false, reason: "EMPTY_TEXT" };
  if (isCanonicalDidacticText(text)) return { valid: true, reason: "CANONICAL_WELCOME" };
  if (!signature) return { valid: false, reason: "INVALID_FORMAT" };

  const canonical = canonicalizeText(text);

  // 1. Support legacy 64-char pure hex signatures (unit tests & backwards compat)
  if (/^[a-f0-9]{64}$/i.test(signature)) {
    const expected = createHmac("sha256", HMAC_SECRET).update(canonical).digest("hex");
    if (signature.length === expected.length) {
      try {
        const a = Buffer.from(signature, "hex");
        const b = Buffer.from(expected, "hex");
        if (a.length === b.length && timingSafeEqual(a, b)) {
          return { valid: true, reason: "VALID" };
        }
      } catch {}
    }
    return { valid: false, reason: "TAMPERED_TEXT" };
  }

  // 2. Parse v1 format: v1.<timestamp>.<actorId>.<hmacHex>
  const parts = signature.split(".");
  if (parts.length !== 4 || parts[0] !== "v1") {
    return { valid: false, reason: "INVALID_FORMAT" };
  }

  const [, tsStr, sigActorId, hmacHex] = parts;
  const timestamp = parseInt(tsStr, 10);
  if (isNaN(timestamp)) {
    return { valid: false, reason: "INVALID_FORMAT" };
  }

  const now = Date.now();

  // Expiration check (15-min TTL)
  if (now - timestamp > SIGNATURE_TTL_MS) {
    return { valid: false, reason: "EXPIRED", timestamp, actorId: sigActorId };
  }

  // Future timestamp clock skew check (max 60 seconds)
  if (timestamp > now + MAX_FUTURE_SKEW_MS) {
    return { valid: false, reason: "FUTURE_TIMESTAMP", timestamp, actorId: sigActorId };
  }

  // Actor binding check (prevent cross-student signature theft)
  if (expectedActorId && sigActorId !== "*" && sigActorId !== expectedActorId) {
    return { valid: false, reason: "ACTOR_MISMATCH", timestamp, actorId: sigActorId };
  }

  // HMAC text integrity check
  const payloadToSign = `v1:${canonical}:${sigActorId}:${timestamp}`;
  const expectedHmac = createHmac("sha256", HMAC_SECRET).update(payloadToSign).digest("hex");

  if (hmacHex.length !== expectedHmac.length) {
    return { valid: false, reason: "TAMPERED_TEXT", timestamp, actorId: sigActorId };
  }

  try {
    const a = Buffer.from(hmacHex, "hex");
    const b = Buffer.from(expectedHmac, "hex");
    if (a.length !== b.length || !timingSafeEqual(a, b)) {
      return { valid: false, reason: "TAMPERED_TEXT", timestamp, actorId: sigActorId };
    }
  } catch {
    return { valid: false, reason: "TAMPERED_TEXT", timestamp, actorId: sigActorId };
  }

  // Replay check
  cleanupReplayTracker();
  let usage = replayTracker.get(signature);
  if (!usage) {
    usage = { count: 0, expires: timestamp + SIGNATURE_TTL_MS };
    replayTracker.set(signature, usage);
  }
  if (usage.count >= MAX_REPLAYS_PER_SIGNATURE) {
    return { valid: false, reason: "REPLAY_EXCEEDED", timestamp, actorId: sigActorId, remainingReplays: 0 };
  }
  usage.count += 1;

  return {
    valid: true,
    reason: "VALID",
    timestamp,
    actorId: sigActorId,
    remainingReplays: MAX_REPLAYS_PER_SIGNATURE - usage.count,
  };
}

/**
 * Standard boolean verification function (preserves 100% backwards compatibility).
 */
export function verifyDidacticSignature(
  text: string,
  signature: string | null | undefined,
  expectedActorId?: string | null
): boolean {
  return verifyDidacticSignatureDetail(text, signature, expectedActorId).valid;
}

/**
 * Resets internal replay cache (primarily for unit and adversarial testing).
 */
export function resetSignatureStateForTesting() {
  replayTracker.clear();
}
